version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.2.0
    container_name: aina-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT_ALLOW_RECOVERY_MODE=true
    restart: unless-stopped

volumes:
  qdrant_storage:
    driver: local