name: aina-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - cudatoolkit=11.8
  - numpy=1.24.3
  - pip=22.3
  - pip:
    - discord.py==2.3.1
    - huggingface-hub==0.14.1
    - transformers==4.30.2
    - sentence-transformers==2.2.2
    - qdrant-client==1.2.0
    - pydantic==1.10.8
    - python-dotenv==1.0.0
    - pillow==9.5.0
    - pyqt5==5.15.9
    - loguru==0.7.0
    - pytest==7.3.1
    - ctransformers==0.2.27
    - llama-cpp-python==0.2.11
    - langchain==0.0.274